version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_snackbar
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"